### ISSUE TITLE
extra keys

### ISSUE THREAD

**Issue by timoline** [Sholofly/ziggonext-python#27]
https://github.com/Sholofly/ziggonext-python/blob/b70d26950c9f96c6e2fbd5578174a6fb40f5516b/ziggonext/const.py#L15

there is also a TV  knob with value TV ;-)

**Comment by timoline** [comment]
found some more....the navigation keys

MediaTopMenu
ArrowUp				
ArrowDown
ArrowLeft
ArrowRight
Enter

**Comment by Sholofly** [comment]
Hi @timoline , thank you for your message. I will look into it soon!

**Comment by Sholofly** [comment]
@timoline Fixed!
