### ISSUE TITLE
Enhancement: Reduce MQTT clients

### ISSUE THREAD

**Issue by nwpr** [Sholofly/ziggonext-python#8]
Every box object is currently using its own MQTT client.
Using one shared client would be more efficient and therefore much better.

**Comment by Sholofly** [comment]
Very good suggestion. Is on my to do list already but I have a lack of time :). Thanks.

**Comment by Sholofly** [comment]
@nwpr I did a change to use one client for all boxes but although it builds, it doesn't gives me the right output. Can you take a look at it?

**Comment by nwpr** [comment]
Hmm, switching the channel works.
But I actually get not mqtt logs at all on log level debug...?

**Comment by nwpr** [comment]
If you add the logger to paho, you get `Caught exception in on_connect: 'str' object has no attribute 'register'`.
So... You are calling
```
for box in self.settop_boxes:
    box.register()
```
in `_on_mqtt_client_connect`. This means that self.settop_boxes only contains strings, not `ZiggoNextBox`objects.

**Comment by Sholofly** [comment]
Thanks, found the issue with your suggestion. I updated te library and the component. Can you confirm your issue is solved?

**Comment by nwpr** [comment]
Yes! Seems fine to me! ☺️

**Comment by nwpr** [comment]
Just wanted to say: the callback feature is 💯!
(I'm only using this python library without HA btw; openHAB is better for my use case)

**Comment by nwpr** [comment]
Just one more thing: please move the mqtt enable_logger directly after the creation of the mqtt client so that the connection attempt and everything else is also logged

**Comment by Sholofly** [comment]
> Just wanted to say: the callback feature is 💯!
> (I'm only using this python library without HA btw; openHAB is better for my use case)

Thank you!
